---

# Einrichtung von GPOs und PSOs
- name: Passwortrichtlinien
  hosts: "{{server_name}}"
  tasks:
  - name: Anpassen der Passwortregulierungen
    ansible.windows.win_powershell:
      script: | 

        # Standardpasswortregeln
        Set-ADDefaultDomainPasswordPolicy -ComplexityEnabled $true -Identity "{{dns_domain_name}}" -MinPasswordLength 8 -PasswordHistoryCount 4 -LockoutDuration "0.01:00:00" -LockoutObservationWindow "0.00:15:00" -LockoutThreshold 5 -MaxPasswordAge "90.00:00:00" -MinPasswordAge "1.00:00:00"

        # Passwortregeln für Benutzeradmins
        New-ADFineGrainedPasswordPolicy -Name "Domain_Admin_PSO" -ComplexityEnabled $true -Precedence 500 -MinPasswordLength 16 -PasswordHistoryCount 8 -LockoutDuration "0.01:00:00" -LockoutObservationWindow "0.00:05:00" -LockoutThreshold 5 -MaxPasswordAge "30.00:00:00" -MinPasswordAge "1.00:00:00"
        Add-ADFineGrainedPasswordPolicySubject "Domain_Admin_PSO" "Domain_Admin_Gruppe"

        # Passwortregeln für Services
        New-ADFineGrainedPasswordPolicy -Name "Service_Admin_PSO" -ComplexityEnabled $true -Precedence 500 -MinPasswordLength 32 -PasswordHistoryCount 16 -LockoutDuration "0.03:00:00" -LockoutObservationWindow "0.00:05:00" -LockoutThreshold 3 -MaxPasswordAge "00.00:00:00" -MinPasswordAge "1.00:00:00"
        Add-ADFineGrainedPasswordPolicySubject "Service_Admin_PSO" "Service_Admin_Gruppe"
