---

# Einrichten eines Domänencontrollers
- name: Einrichten eines Domänencontrollers
  hosts: "{{server_name}}"
  tasks:
  - name: Installieren des AD
    ansible.windows.win_feature: 
        name: AD-Domain-Services
        include_management_tools: true
        include_sub_feature: true
        state: present

  - name: Installieren der Domaene
    ansible.windows.win_domain: 
      dns_domain_name: "{{dns_domain_name}}"
      safe_mode_password: "{{safe_mode_pw_ad_ds}}"
      install_dns: true
    register: domain

  - name: DNS einrichten
    ansible.windows.win_dns_client:
      adapter_names: "*"
      dns_servers:
      - "{{dc_ip_address}}"
      - 127.0.0.1
    when: domain.reboot_required

  - name: Neustarten des Servers
    ansible.windows.win_reboot:
      msg: "Installing AD. Rebooting..."
      pre_reboot_delay: 15
      reboot_timeout: 3600
    when: domain.reboot_required